CREATE TABLE IF NOT EXISTS Users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    passwd TEXT,
    role VARCHAR(20) CHECK (role IN ('ADMIN', 'USER')),
    telegram TEXT UNIQUE,
    email TEXT UNIQUE,
    phone TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS OtpConfig(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lifetime INTEGER NOT NULL CHECK(lifetime >= 0),
    sign_number INTEGER NOT NULL CHECK(sign_number >= 5)
);

-- Создаем функцию для проверки всех элементов массива
CREATE ALIAS IF NOT EXISTS IS_VALID_OTP AS $$
    boolean isValidOtp(Integer[] codes) {
        for (int num : codes) {
            if (num < 0 || num > 9) {
                return false;
            }
        }
        return true;
    }
$$;

CREATE TABLE IF NOT EXISTS OtpCodes(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code INTEGER ARRAY NOT NULL,
    request_time TIMESTAMP NOT NULL,
    status VARCHAR(20) CHECK (status IN ('ACTIVE', 'EXPIRED', 'USED')),
    FOREIGN KEY(user_id) REFERENCES Users(id),
    CHECK (IS_VALID_OTP(code))
);